### PR TITLE
fix gcc and clang 9 images

### LINKED ISSUE #233: gcc9: error when running apt update
### Description of Problem, Request, or Question

The `conanio/gcc9` image is still running Ubuntu 19.10, which is officially EOL. Running `apt update` is causing errors for missing release files.

### Environment Details
* Conan Docker Tools image: **conanio/gcc9**
* Operating System: **MacOS**
* Operation System Version: **10.15.17**

### Steps to reproduce (Include if Applicable)

1) Download and run the latest `conanio/gcc9` image
2) Run `sudo apt update`

### Build logs (Include if Available)

```
conan@69a052cec648:~$ sudo apt update
Ign:1 http://security.ubuntu.com/ubuntu eoan-security InRelease
Ign:2 http://archive.ubuntu.com/ubuntu eoan InRelease
Err:3 http://security.ubuntu.com/ubuntu eoan-security Release
  404  Not Found [IP: 91.189.91.39 80]
Ign:4 http://archive.ubuntu.com/ubuntu eoan-updates InRelease
Ign:5 http://archive.ubuntu.com/ubuntu eoan-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu eoan Release
  404  Not Found [IP: 91.189.88.152 80]
Err:7 http://archive.ubuntu.com/ubuntu eoan-updates Release
  404  Not Found [IP: 91.189.88.152 80]
Err:8 http://archive.ubuntu.com/ubuntu eoan-backports Release
  404  Not Found [IP: 91.189.88.152 80]
Reading package lists... Done
E: The repository 'http://security.ubuntu.com/ubuntu eoan-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu eoan-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu eoan-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### PR DESCRIPTION
**Pull request by ericLemanissier**
eoan is EOL
fixes #233

Changelog: (Feature | Fix | Bugfix): Describe here your pull request

- [X] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [X] I've read the [Contributing guide](https://github.com/conan-io/conan-docker-tools/blob/master/.github/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008) style guides for Python code.
- [ ] I've followed the [Best Practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) guides for Dockerfile.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
currently it fails with 
```
E: The repository 'http://old-releases.ubuntu.com/ubuntu eoan Release' does not have a Release file.
E: The repository 'http://old-releases.ubuntu.com/ubuntu eoan-updates Release' does not have a Release file.
E: The repository 'http://old-releases.ubuntu.com/ubuntu eoan-backports Release' does not have a Release file.
E: The repository 'http://old-releases.ubuntu.com/ubuntu eoan-security Release' does not have a Release file.
```

**Comment by uilianries** [comment]
@ericLemanissier Yes, I have the same behavior. take a look at https://github.com/conan-io/conan-docker-tools/pull/235

**Comment by jgsogo** [comment]
We need this PR asap, so far it looks like all we can do is to wait (https://askubuntu.com/questions/1299282/ubuntu-19-10-eoan-can-not-fetch-old-releases), those repos will eventually be available.

**Comment by Croydon** [comment]
According to https://askubuntu.com/questions/1299151/no-release-file-for-eoan-on-old-releases-ubuntu-com the `Release` file was missing here: http://old-releases.ubuntu.com/ubuntu/dists/eoan/ and hence the errors

Now the `Release` file is there. Can someone please restart the CI to see if it works now?

**Comment by Croydon** [comment]
Spoiler: CentOS 6 will fail until it is removed: https://github.com/conan-io/conan-docker-tools/pull/236

**Comment by uilianries** [comment]
> According to [askubuntu.com/questions/1299151/no-release-file-for-eoan-on-old-releases-ubuntu-com](https://askubuntu.com/questions/1299151/no-release-file-for-eoan-on-old-releases-ubuntu-com) the `Release` file was missing here: [http://old-releases.ubuntu.com/ubuntu/dists/eoan](http://old-releases.ubuntu.com/ubuntu/dists/eoan/) and hence the errors
> 
> Now the `Release` file is there. Can someone please restart the CI to see if it works now?


It's working again!!!!!

```
root@1ce181898b8c:/# cat /etc/apt/sources.list
deb http://old-releases.ubuntu.com/ubuntu/ eoan main restricted
deb http://old-releases.ubuntu.com/ubuntu/ eoan-updates main restricted

deb http://old-releases.ubuntu.com/ubuntu/ eoan universe
deb-src http://old-releases.ubuntu.com/ubuntu/ eoan universe
deb http://old-releases.ubuntu.com/ubuntu/ eoan-updates universe
deb-src http://old-releases.ubuntu.com/ubuntu/ eoan-updates universe

deb http://old-releases.ubuntu.com/ubuntu/ eoan multiverse
deb http://old-releases.ubuntu.com/ubuntu/ eoan-updates multiverse

deb http://old-releases.ubuntu.com/ubuntu/ eoan-backports main restricted universe multiverse

deb http://old-releases.ubuntu.com/ubuntu/ eoan-security main restricted
deb http://old-releases.ubuntu.com/ubuntu/ eoan-security universe
deb-src http://old-releases.ubuntu.com/ubuntu/ eoan-security universe
deb http://old-releases.ubuntu.com/ubuntu/ eoan-security multiverse
root@1ce181898b8c:/# apt-get update
Get:1 http://old-releases.ubuntu.com/ubuntu eoan InRelease [255 kB]
Get:2 http://old-releases.ubuntu.com/ubuntu eoan-updates InRelease [97.5 kB]
Get:3 http://old-releases.ubuntu.com/ubuntu eoan-backports InRelease [88.8 kB]
Get:4 http://old-releases.ubuntu.com/ubuntu eoan-security InRelease [97.5 kB]
Get:5 http://old-releases.ubuntu.com/ubuntu eoan/universe Sources [12.3 MB]
Get:6 http://old-releases.ubuntu.com/ubuntu eoan/universe amd64 Packages [11.6 MB]                                                                                                                                                          
Get:7 http://old-releases.ubuntu.com/ubuntu eoan/restricted amd64 Packages [22.7 kB]                                                                                                                                                        
Get:8 http://old-releases.ubuntu.com/ubuntu eoan/multiverse amd64 Packages [188 kB]                                                                                                                                                         
Get:9 http://old-releases.ubuntu.com/ubuntu eoan/main amd64 Packages [1277 kB]                                                                                                                                                              
Get:10 http://old-releases.ubuntu.com/ubuntu eoan-updates/universe Sources [54.7 kB]                                                                                                                                                        
Get:11 http://old-releases.ubuntu.com/ubuntu eoan-updates/multiverse amd64 Packages [1074 B]                                                                                                                                                
Get:12 http://old-releases.ubuntu.com/ubuntu eoan-updates/main amd64 Packages [431 kB]                                                                                                                                                      
Get:13 http://old-releases.ubuntu.com/ubuntu eoan-updates/universe amd64 Packages [283 kB]                                                                                                                                                  
Get:14 http://old-releases.ubuntu.com/ubuntu eoan-updates/restricted amd64 Packages [56.6 kB]                                                                                                                                               
Get:15 http://old-releases.ubuntu.com/ubuntu eoan-backports/universe amd64 Packages [4108 B]                                                                                                                                                
Get:16 http://old-releases.ubuntu.com/ubuntu eoan-backports/main amd64 Packages [669 B]                                                                                                                                                     
Get:17 http://old-releases.ubuntu.com/ubuntu eoan-security/universe Sources [33.0 kB]                                                                                                                                                       
Get:18 http://old-releases.ubuntu.com/ubuntu eoan-security/universe amd64 Packages [221 kB]                                                                                                                                                 
Get:19 http://old-releases.ubuntu.com/ubuntu eoan-security/restricted amd64 Packages [56.6 kB]                                                                                                                                              
Get:20 http://old-releases.ubuntu.com/ubuntu eoan-security/multiverse amd64 Packages [1074 B]                                                                                                                                               
Get:21 http://old-releases.ubuntu.com/ubuntu eoan-security/main amd64 Packages [328 kB]                                                                                                                                                     
Fetched 27.4 MB in 16s (1743 kB/s)                                                                                                                                                                                                          
Reading package lists... Done
root@1ce181898b8c:/# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Ubuntu 19.10"
```

[Back on the Rails](https://media3.giphy.com/media/fQoiuYNXHfCa8iq5OK/giphy.gif)

**Comment by uilianries** [comment]
@ericLemanissier Could you please change to "Ready for Review" state?

**Review by Croydon — APPROVED** [review]

**Comment by ericLemanissier** [comment]
@uilianries @jgsogo can we merge this one ?

**Pull request merged**
