### PR TITLE
migrate artful dpkg repo to old-releases.ubuntu.com

### PR DESCRIPTION
**Pull request by ericLemanissier**

### CODE REVIEW

**Comment by SSE4** [comment]
something goes wrong with OpenJDK installation
```
 ---> Running in 12b209f83687
E: The repository &#x27;http:&#x2F;&#x2F;security.ubuntu.com&#x2F;ubuntu artful-security Release&#x27; does not have a Release file.‌
E: The repository 'http://archive.ubuntu.com/ubuntu artful Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu artful-updates Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu artful-backports Release' does not have a Release file.
Service &#x27;gcc6-jnlp-slave&#x27; failed to build: The command &#x27;&#x2F;bin&#x2F;sh -c &#x2F;tmp&#x2F;install-openjdk-ppa.sh     &amp;&amp; apt-get -qq update     &amp;&amp; apt-get -q install -y openjdk-8-jre-headless curl     &amp;&amp; apt-get -q clean -y     &amp;&amp; rm -rf &#x2F;var&#x2F;lib&#x2F;apt&#x2F;lists&#x2F;*     &amp;&amp; rm -f &#x2F;var&#x2F;cache&#x2F;apt&#x2F;*.bin     &amp;&amp; pip3 install --no-cache virtualenv     &amp;&amp; curl --create-dirs -sSLo &#x2F;usr&#x2F;share&#x2F;jenkins&#x2F;slave.jar https:&#x2F;&#x2F;repo.jenkins-ci.org&#x2F;public&#x2F;org&#x2F;jenkins-ci&#x2F;main&#x2F;remoting&#x2F;${AGENT_VERSION}&#x2F;remoting-${AGENT_VERSION}.jar     &amp;&amp; chmod 755 &#x2F;usr&#x2F;share&#x2F;jenkins     &amp;&amp; chmod 644 &#x2F;usr&#x2F;share&#x2F;jenkins&#x2F;slave.jar     &amp;&amp; chmod +x &#x2F;opt&#x2F;entrypoint.sh &#x2F;usr&#x2F;local&#x2F;bin&#x2F;jenkins-slave&#x27; returned a non-zero code: 100‌
```

**Comment by Croydon** [comment]
We haven't done such a thing with e.g. precise (gcc 4.6) either, is this really necessary? Maybe we just need to rebuild with the latest image from Docker hub?

I don't believe that every Ubuntu installation out there needs to manually switch their repositories

**Comment by ericLemanissier** [comment]
@SSE4 the problem with openjdk installation is what my patch solves. It cannot work because the corrected docker image is not on docker hub

**Comment by ericLemanissier** [comment]
@Croydon precise is still available in http://archive.ubuntu.com/ubuntu/dists/ contrary to artful
All the image based on wily and yakkety  are already using http://old-releases.ubuntu.com/releases/ (eg https://github.com/conan-io/conan-docker-tools/blob/master/gcc_5.2/Dockerfile#L10 and https://github.com/conan-io/conan-docker-tools/blob/master/gcc_6.2/sources.list)

**Comment by SSE4** [comment]
@ericLemanissier you're right, that cannot pass in one shot :( I've faced the same problem with Android images, build needs to run twice.
however, Clang 7 seems to be broken:
```

The following packages have unmet dependencies:
 g++-multilib : Depends: cpp (= 4:8.2.0-1ubuntu1) but 4:8.3.0-1ubuntu1.1 is to be installed
                Depends: gcc-multilib (= 4:8.2.0-1ubuntu1) but 4:8.3.0-1ubuntu1.1 is to be installed
                Depends: g++ (= 4:8.2.0-1ubuntu1) but 4:8.3.0-1ubuntu1.1 is to be installed
E: Unable to correct problems, you have held broken packages.‌
Service &#x27;clang7&#x27; failed to build: The command &#x27;&#x2F;bin&#x2F;sh -c dpkg --add-architecture i386     &amp;&amp; apt-get -qq update     &amp;&amp; apt-get install -y --no-install-recommends        sudo=1.8.*        wget=1.19.*        git=1:2.19.*        g++-multilib=4:8.2.*        clang-7=1:7-*        make=4.2.*        libc6-dev-i386=2.*        libgmp-dev=2:6.1.*        libmpfr-dev=4.0.*        libmpc-dev=1.1.*        nasm=2.13*        dh-autoreconf=19        libffi-dev=3.2.*        libssl-dev=1*        ninja-build=1.8.*        libc++-dev=6.0.*        libc++-dev:i386=6.0.*        libc++abi-dev=6.0.*        libc++abi-dev:i386=6.0.*        pkg-config=0.29.*        subversion=1.10.*        zlib1g-dev=1:1.*        libbz2-dev=1.*        libsqlite3-dev=3.*        libreadline-dev=7.*        xz-utils=5.*        curl=7.*        libncurses5-dev=6.*        libncursesw5-dev=6.*        liblzma-dev=5.*        ca-certificates        autoconf-archive     &amp;&amp; update-alternatives --install &#x2F;usr&#x2F;bin&#x2F;clang++ clang++ &#x2F;usr&#x2F;bin&#x2F;clang++-7 100     &amp;&amp; update-alternatives --install &#x2F;usr&#x2F;bin&#x2F;clang clang &#x2F;usr&#x2F;bin&#x2F;clang-7 100     &amp;&amp; update-alternatives --install &#x2F;usr&#x2F;bin&#x2F;cc cc &#x2F;usr&#x2F;bin&#x2F;clang-7 100     &amp;&amp; update-alternatives --install &#x2F;usr&#x2F;bin&#x2F;c++ c++ &#x2F;usr&#x2F;bin&#x2F;clang++-7 100     &amp;&amp; update-alternatives --install &#x2F;usr&#x2F;bin&#x2F;cpp cpp &#x2F;usr&#x2F;bin&#x2F;clang++-7 100     &amp;&amp; ln -s &#x2F;usr&#x2F;include&#x2F;locale.h &#x2F;usr&#x2F;include&#x2F;xlocale.h     &amp;&amp; rm -rf &#x2F;var&#x2F;lib&#x2F;apt&#x2F;lists&#x2F;*     &amp;&amp; wget -q --no-check-certificate https:&#x2F;&#x2F;cmake.org&#x2F;files&#x2F;v3.14&#x2F;cmake-3.14.3-Linux-x86_64.tar.gz     &amp;&amp; tar -xzf cmake-3.14.3-Linux-x86_64.tar.gz        --exclude=bin&#x2F;cmake-gui        --exclude=doc&#x2F;cmake        --exclude=share&#x2F;cmake-3.12&#x2F;Help     &amp;&amp; cp -fR cmake-3.14.3-Linux-x86_64&#x2F;* &#x2F;usr     &amp;&amp; rm -rf cmake-3.14.3-Linux-x86_64     &amp;&amp; rm cmake-3.14.3-Linux-x86_64.tar.gz     &amp;&amp; groupadd 1001 -g 1001     &amp;&amp; groupadd 1000 -g 1000     &amp;&amp; groupadd 2000 -g 2000     &amp;&amp; groupadd 999 -g 999     &amp;&amp; useradd -ms &#x2F;bin&#x2F;bash conan -g 1001 -G 1000,2000,999     &amp;&amp; printf &quot;conan:conan&quot; | chpasswd     &amp;&amp; adduser conan sudo     &amp;&amp; printf &quot;conan ALL= NOPASSWD: ALL\\n&quot; &gt;&gt; &#x2F;etc&#x2F;sudoers     &amp;&amp; wget --no-check-certificate --quiet -O &#x2F;tmp&#x2F;pyenv-installer https:&#x2F;&#x2F;github.com&#x2F;pyenv&#x2F;pyenv-installer&#x2F;raw&#x2F;master&#x2F;bin&#x2F;pyenv-installer     &amp;&amp; chmod +x &#x2F;tmp&#x2F;pyenv-installer     &amp;&amp; &#x2F;tmp&#x2F;pyenv-installer     &amp;&amp; rm &#x2F;tmp&#x2F;pyenv-installer     &amp;&amp; update-alternatives --install &#x2F;usr&#x2F;bin&#x2F;pyenv pyenv &#x2F;opt&#x2F;pyenv&#x2F;bin&#x2F;pyenv 100     &amp;&amp; PYTHON_CONFIGURE_OPTS=&quot;--enable-shared&quot; pyenv install 3.7.1     &amp;&amp; pyenv global 3.7.1     &amp;&amp; pip install -q --upgrade --no-cache-dir pip     &amp;&amp; pip install -q --no-cache-dir conan conan-package-tools     &amp;&amp; chown -R conan:1001 &#x2F;opt&#x2F;pyenv     &amp;&amp; find &#x2F;opt&#x2F;pyenv -iname __pycache__ -print0 | xargs -0 rm -rf     &amp;&amp; update-alternatives --install &#x2F;usr&#x2F;bin&#x2F;python python &#x2F;opt&#x2F;pyenv&#x2F;shims&#x2F;python 100     &amp;&amp; update-alternatives --install &#x2F;usr&#x2F;bin&#x2F;python3 python3 &#x2F;opt&#x2F;pyenv&#x2F;shims&#x2F;python3 100     &amp;&amp; update-alternatives --install &#x2F;usr&#x2F;bin&#x2F;pip pip &#x2F;opt&#x2F;pyenv&#x2F;shims&#x2F;pip 100     &amp;&amp; update-alternatives --install &#x2F;usr&#x2F;bin&#x2F;pip3 pip3 &#x2F;opt&#x2F;pyenv&#x2F;shims&#x2F;pip3 100&#x27; returned a non-zero code: 100‌

```

**Comment by SSE4** [comment]
which you didn't touch... weird

**Comment by Croydon** [comment]
I run into the same problem with Clang 7 here: https://github.com/conan-io/conan-docker-tools/pull/129

And I also believe that this pull request can't pass https://github.com/conan-io/conan-docker-tools/pull/129#issuecomment-489871164

Does Azure support build stages? This would solve it at least for the master branch

**Pull request merged**
