### PR TITLE
modern: bump base to Bionic

### PR DESCRIPTION
**Pull request by ericLemanissier**
Until now, all modern images are based on Xenial, which is "End of standard support" since April 2021. It is a problem for projects like Qt which do not support Xenial any more. In the case of Qt, the compilation fails because xenial's system package for xcb-randr0 is too old (cf https://github.com/conan-io/conan-center-index/pull/12620#issuecomment-1235350713). I don't think there is any acceptable workaround, cf https://github.com/conan-io/conan-center-index/pull/12620#issuecomment-1247962304)

CC @jgsogo @uilianries @danimtb @jcar87

Changelog: Fix : modern docker image are based on Ubuntu Bionic

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [ ] I've read the [Contributing guide](https://github.com/conan-io/conan-docker-tools/blob/master/.github/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008) style guides for Python code.
- [ ] I've followed the [Best Practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) guides for Dockerfile.

### CODE REVIEW

**Comment by uilianries** [comment]
My hand shaking to merge it at once!

**Comment by uilianries** [comment]
It failed due a server error (not our side). Just restarted it now.

**Comment by ericLemanissier** [comment]
> My hand shaking to merge it at once!

:D Do we have a consensus that migrating to bionic is ok ?

**Comment by uilianries** [comment]
@ericLemanissier we still need some data, number of packages downloaded related to that distro.

Personally, I'm inclined to update it too.

**Comment by uilianries** [comment]
```
Archive:  ninja-linux.zip

  inflating: ninja                   

E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
```

the clang-builder requires one of these packages

**Review by AndreyMlashkin — APPROVED** [review]

**Comment by uilianries** [comment]
We will discuss next week about this PR, hope we can update it soon.

**Comment by ericLemanissier** [comment]
for the record, all qt pull requests have been blocked by this issue [for a month](https://github.com/conan-io/conan-center-index/pull/12620#issuecomment-1235350713). As a consequence the last two versions of qt are not available on CCI. Some decision has to be taken one way or the other

**Comment by ericLemanissier** [comment]
@uilianries do we have a plan? Or should affected recipes raise ConanInvalidConfiguration based on lsb_release ?

**Comment by uilianries** [comment]
@ericLemanissier I built all images and I gonna test it today. Next week, if all occurs fine, we can start to migrate.

**Comment by uilianries** [comment]
I did some tests today and looks good.

I installed Boost, Poco, Cmake, opencv, ffmpeg and other pre-built packages from Conan Center, to a GCC 11 Ubuntu 18.04 from this PR and executed the test package, using option shared with libstdc++/11 combination. So far, no runtime errors.

**Review by danimtb — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
@ericLemanissier Thank you for updating it! This PR has been merged.

**Pull request merged**
