### PR TITLE
Fix gcc 7.x Docker image test

### PR DESCRIPTION
**Pull request by ovidiub13**
Gcc-6 is not installed. This throws a `file not found` error, so I'm proposing to remove it.

### CODE REVIEW

**Comment by ovidiub13** [comment]
In Ubuntu Artful there is no official package for GCC 7.1 anymore, just GCC 7.2.
I've updated all references to 7.2.

**Comment by lasote** [comment]
But then we are losing the 7.1 image... Breaking existing builds that used it. We should somehow force install 7.1 in an image

**Comment by ovidiub13** [comment]
@lasote I've tried. The package does not exist in the Ubuntu repository.

**Comment by lasote** [comment]
Yeah, I saw it too. It makes no sense, thanks for open this discussion. It's on my last PR included.

**Pull request closed without merging**
