### PR TITLE
Update python version to 3.8.0

### LINKED ISSUE #150: Update Python version to 3.8
### Description of Problem, Request, or Question
[Python 3.8](https://docs.python.org/3/whatsnew/3.8.html) is available for [download](https://www.python.org/downloads/release/python-380/)

### PR DESCRIPTION
**Pull request by uilianries**
Update python version used by Docker images
closes #150 
Changelog: Feature: Update python version to 3.8.0

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan-docker-tools/blob/master/.github/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008) style guides for Python code.
- [x] I've followed the [Best Practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) guides for Dockerfile.

### CODE REVIEW

**Comment by danimtb** [comment]
Conan does not support 3.8 as there are some issues reported. So we cannot update the images yet

**Comment by uilianries** [comment]
Conan supports Python 3.8 since https://github.com/conan-io/conan/pull/6439

**Comment by uilianries** [comment]
@danimtb I think we are good now.

**Comment by danimtb** [comment]
This PR also unifies the Python version used in all images, right?

**Comment by uilianries** [comment]
@danimtb Yes, all images will run Python 3.8.5

**Comment by memsharded** [comment]
> @danimtb Yes, all images will run Python 3.8.5

Why? Wouldn't it be a bit more conservative to run something more backwards compatible. Running with latest Python, users can use some newer Python features that will only work in Python 3.8, like the walrus operator (then breaking ConanCenter for everyone using Python<3.8), while doing something in Python 3.6 that breaks in Python 3.8 is way more unlikely.

**Comment by danimtb** [comment]
I see we were already using Python 3.7.5 in almost all images so for me it has more value the unification of the version than the update. I don't know what has been the policy updating python in conan-docker-tools over the time, but I tend to think the same way as @memsharded, is the update really needed? do we have users asking for this change?

**Comment by uilianries** [comment]
Not really required for now, closing

**Pull request closed without merging**
