### PR TITLE
#100 Update autoconf and automake

### LINKED ISSUE #100: update autoconf, automake to recent versions for gcc7-centos6 images
we have to update autoconf & automake versions on our `gcc7-centos6` images
currently, [gettext_installer](https://github.com/bincrafters/conan-gettext_installer) [fails](https://travis-ci.com/bincrafters/conan-gettext_installer/jobs/171421611) with the following error:
```
aclocal.m4:17: warning: this file was generated for autoconf 2.69.
You have another version of autoconf.  It may work, but is not guaranteed to.
If you have problems, you may need to regenerate the build system entirely.
To do so, use the procedure documented by the package, typically 'autoreconf'.
configure.ac:26: error: Autoconf version 2.65 or higher is required
aclocal.m4:156: AM_INIT_AUTOMAKE is expanded from...
configure.ac:26: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
WARNING: 'autoconf' is probably too old.
         You should only need it if you modified 'configure.ac',
         or m4 files included by it.
         The 'autoconf' program is part of the GNU Autoconf package:
         <http://www.gnu.org/software/autoconf/>
         It also requires GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [Makefile:402: configure] Error 63
```
running `autoreconf -fiv` doesn't cure this issue, as project uses macro from newer automake version.
this might not be easy to do, EPEL release has [autoconf268](https://www.rpmfind.net/linux/rpm2html/search.php?query=autoconf268) package, but no recent automake. this may end up into building autoconf/automake from source, or building RPM packages.

/cc @uilianries

### LINKED ISSUE #105: gcc7-centos does not support system_requires: sudo -A fails
Installing system requirements using the `tools.SystemPackageTool` fails in the `gcc7-centos` docker
The error is:
```
Running: sudo -A yum update -y
/var/tmp/sclH4Ekle: line 8: -A: command not found
```
travis: https://travis-ci.com/madebr/conan-ps2_toolchain_installer/jobs/180446149#L596

This can be reproduced in interactive mode:
```
$ docker run -t -i --rm -v /tmp:/home/conan/project:Z conanio/gcc7-centos6 /bin/bash
[conan@e5b2b8cb2901 ~]$ sudo -A ls
/var/tmp/sclvoMvA6: line 8: -A: command not found
```

### PR DESCRIPTION
**Pull request by uilianries**
Installed the latest versions of autoconf, automake.

fixes #100

### CODE REVIEW

**Comment by madebr** [comment]
FYI: updating sudo is not required for fixing #105 if you remove `/opt/rh/devtoolset-7/root/usr/bin/sudo`.
`sudo` installed by centos has support for the `-A` option.

Removing that file is fine, if you don't use the gcc toolchain while using sudo.

**Comment by lasote** [comment]
@uilianries is this ready or you can accept the @madebr suggest?

**Comment by uilianries** [comment]
@lasote We can accept the PR #106 before to merge this one

**Comment by uilianries** [comment]
@madebr I removed all changes related to sudo from this PR. Let's use your PR #106

**Pull request merged**
