### PR TITLE
Git - test minimum version

### PR DESCRIPTION
**Pull request by jgsogo**
After https://github.com/conan-io/conan-docker-tools/pull/358 it was expected that the new Git version would break current tests.

Here I'm modifying the tests, now we check the minimum boundary for Git, the upper boundary is open.

---

NOTE.- If anyone knows how to install a fixed version, it would be great to hear it 🙌

### CODE REVIEW

**Comment by uilianries** [comment]
To install a fixed version you have to pass ==, like `apt install git==<version>` But again, it doesn't work on Ubuntu, if they update the version, they also remove the current version, then your installation is broken. We had a series of problems in the past trying to use fixed versions, at some point, Luis and me agreed in don't using fixed versions.

**Comment by jgsogo** [comment]
We need fixed versions as much as possible. Everything around `conan-center-index` is based on stability and reproducibility. If we introduce here some change and things start to fail in that CI we will have a problem hard to find (no one changed anything) and hard to fix (how to downgrade the version to the one that works). That issue could lead to several days of downtime in CCI until we are able to find, implement and deploy the fix. We don't want that to happen 😄

**Comment by uilianries** [comment]
Again, we don't have that control. Once ubuntu updates a package version, it will need to update or we will be broken. You can enforce a version, but it won't help as soon we have a new update, you will need to update and that's it. The only advantage is keeping a git history about which version was used during that time, but is something we can acquire form ubuntu packages too.
If you want to reproduce everything and lock versions, my suggestion is building from source, distros are not so cool like Conan, they only support the latest version.

**Comment by jgsogo** [comment]
That's why I left the comment in the description, in case anyone knows how to do it with the system package manager. 

When we started to develop these modern images we agreed that we were not going to use Conan to install binaries (because of the chicken-and-egg problem), but after https://github.com/conan-io/conan-docker-tools/pull/370, maybe we decide to use it and we change our minds. If that's the case, we could install Git using Conan, and other tools as well.

**Comment by jgsogo** [comment]
After merging (and CI passes in `master`), we need to trigger the generation of these docker images for ConanCenter.

**Review by uilianries — COMMENTED** [review]
LGTM

**Pull request merged**
