### PR TITLE
clang: unable ENABLE_LINKER_BUILD_ID

### PR DESCRIPTION
**Pull request by marxin**
Similarly to GCC, enable emission of .note.gnu.build-id for debug-info packages.

Related to: https://github.com/conan-io/conan-docker-tools/pull/531

### CODE REVIEW

**Review by uilianries — APPROVED** [review]
Found Ubuntu and Arch using the follow option:

- https://git.launchpad.net/ubuntu/+source/llvm-toolchain-11/tree/debian/rules?h=ubuntu/focal-devel#n384
- https://gitlab.archlinux.org/archlinux/packaging/packages/clang/-/blob/main/PKGBUILD#L102
-

**Comment by marxin** [comment]
May I please remind this?

**Comment by uilianries** [comment]
@marxin Conan Center Index is still in maintenance and our efforts right now are focused on it. Only on next week I'll be able to check this PR, because I need more tests. Thank you.

**Comment by marxin** [comment]
Hope the situation with CCI is better now. (Btw. I really like the new design).
May I please remind you this PR?

**Review by uilianries — APPROVED** [review]
I just tested locally and all looks okay, I did not find any incompatibility problem with current packages in Conan Center.

Let's wait for the CI pass, then we can merge it. 

Thank you @marxin !

**Pull request merged**
