### PR TITLE
Dr. LLVM How I Learned to Stop Worrying and Love the unwind

### LINKED ISSUE #449: Clang 13 links libllvm-unwind to package binaries
### Description of Problem, Request, or Question

This error only happened, because Protobuf distributes executable + libraries and requires C++ libraries.
Regularly, we remove the compiler from the package ID, when a package only contains binaries, so we only provide binaries built by GCC
For some reason Clang 13 is linking its internal libunwind, which is shared.

When building Clang, it required libunwind, and it has an internal implementation. However, we observed that in case we have a package which requires libunwind and Conan provide it, Clang would ignore and use its internal version. So, to avoid any name collision and to enforce Clang to use Conan’s libunwind, we renamed to libllvm-unwind.

Reported case: https://github.com/conan-io/conan-center-index/issues/11497

### Environment Details
* Conan Docker Tools image: **conanio/clang13-ubuntu16.04:1.50.0**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**
* Python version (If you are building some image): **python 3.7.0**

### Steps to reproduce (Include if Applicable)

```
conan install protobuf/3.21.1@
${HOME}/.conan/data/protobuf/3.21.1/_/_/package/8bf80f61e626c664a94fa5752cc1b7e58b9853bc/bin/protoc --version
```

### PR DESCRIPTION
**Pull request by uilianries**
After talking with @jcar87, it was concluded that Clang still needs [libgcc_s](https://refspecs.linuxbase.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/libgcc-s.html) and offering only libunwind is not well supported. Only [Brew formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/llvm.rb#L165-L173) for Clang is adopting free GCC usage. On Linux, this scenario is still not possible.

As all Docker images have a native `libgcc_s` installed, so we don't need to install anything extra.

**TO BE CHECKED**
- We need to check the compatibility between new packages generated with Clang + libgcc_s vs clang + libunwind. Otherwise, it will break Conan Center.

fixes #449 

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [ ] I've read the [Contributing guide](https://github.com/conan-io/conan-docker-tools/blob/master/.github/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008) style guides for Python code.
- [ ] I've followed the [Best Practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) guides for Dockerfile.

### CODE REVIEW

**Comment by uilianries** [comment]
It should be worked at first try. At least, Clang 13 worked locally, and unwind is no longer listed:

```
$ clang++ -v hello.cpp -v
clang version 13.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
Found candidate GCC installation: /usr/local/bin/../lib/gcc/x86_64-linux-gnu/10.3.0
Selected GCC installation: /usr/local/bin/../lib/gcc/x86_64-linux-gnu/10.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/local/bin/clang-13" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name hello.cpp -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -v -v -fcoverage-compilation-dir=/home/conan -resource-dir /usr/local/lib/clang/13.0.0 -internal-isystem /usr/local/bin/../lib/gcc/x86_64-linux-gnu/10.3.0/../../../../include/c++/10.3.0 -internal-isystem /usr/local/bin/../lib/gcc/x86_64-linux-gnu/10.3.0/../../../../include/c++/10.3.0/x86_64-linux-gnu -internal-isystem /usr/local/bin/../lib/gcc/x86_64-linux-gnu/10.3.0/../../../../include/c++/10.3.0/backward -internal-isystem /usr/local/lib/clang/13.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/local/bin/../lib/gcc/x86_64-linux-gnu/10.3.0/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir=/home/conan -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/hello-242f42.o -x c++ hello.cpp
clang -cc1 version 13.0.0 based upon LLVM 13.0.0 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/usr/local/bin/../lib/gcc/x86_64-linux-gnu/10.3.0/../../../../x86_64-linux-gnu/include"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/bin/../lib/gcc/x86_64-linux-gnu/10.3.0/../../../../include/c++/10.3.0
 /usr/local/bin/../lib/gcc/x86_64-linux-gnu/10.3.0/../../../../include/c++/10.3.0/x86_64-linux-gnu
 /usr/local/bin/../lib/gcc/x86_64-linux-gnu/10.3.0/../../../../include/c++/10.3.0/backward
 /usr/local/lib/clang/13.0.0/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
 "/usr/local/bin/ld" -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out /usr/lib/x86_64-linux-gnu/crt1.o /usr/lib/x86_64-linux-gnu/crti.o /usr/local/bin/../lib/gcc/x86_64-linux-gnu/10.3.0/crtbegin.o -L/usr/local/bin/../lib/gcc/x86_64-linux-gnu/10.3.0 -L/usr/local/bin/../lib/gcc/x86_64-linux-gnu/10.3.0/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/local/bin/../lib -L/lib -L/usr/lib /tmp/hello-242f42.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/local/bin/../lib/gcc/x86_64-linux-gnu/10.3.0/crtend.o /usr/lib/x86_64-linux-gnu/crtn.o
```

**Review by jcar87 — APPROVED** [review]
LGTM! Thanks for fixing this so quickly.

I have compared the linker flags emitted and they match the ones emitted by other clang distributions

**Comment by uilianries** [comment]
@jcar87 Thank you very much! Now I'll run some package (protobuf is a good candidate) on the new clang13 image, but I'll will install the pre-built package from Conan Center, which used the old Docker image with libunwind. 

I guess they will be compatible, but we will need to package libunwind on those new images.

**Comment by uilianries** [comment]
We still need to build and install `libunwind` due the packages in Conan Center. However, we will no longer link `libunwind` using Clang.

**Comment by uilianries** [comment]
Doing more tests, now with Poco, build with Clang 13, but current one in Conan Center.

Poco requires `libllvm-unwind`, which is expected. So, any next library or example which requires it, will need `libllvm-unwind`. This new patch will enforce `libgcc_s` with clang and will keep `libllvm-unwind` installed for the legacy. So it passed with Poco.

With a new `clang13-ubuntu16.04:1.50.0` image, using `libgcc_s`, consuming Poco and building all dependencies from source, I have:

```
conan create .  -s compiler.libcxx=libc++ -o *:shared=True --build
....
conan@8e37cbcc7016:/tmp$ ldd /tmp/test_package/build/1ec0a9bfb154f77474f4115e2233eab7c4463c39/bin/example 
	linux-vdso.so.1 =>  (0x00007ffe3835d000)
	libfoo.so => /home/conan/.conan/data/foo/0.1/_/_/package/bacdc78613e66cfe43bfa9cd5891b0c007ae5b19/lib/libfoo.so (0x00007f70e7b0f000)
	libPocoDataMySQL.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoDataMySQL.so.91 (0x00007f70e7adb000)
	libPocoDataPostgreSQL.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoDataPostgreSQL.so.91 (0x00007f70e7a75000)
	libPocoDataSQLite.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoDataSQLite.so.91 (0x00007f70e7a02000)
	libPocoEncodings.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoEncodings.so.91 (0x00007f70e7922000)
	libPocoJWT.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoJWT.so.91 (0x00007f70e78bc000)
	libPocoMongoDB.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoMongoDB.so.91 (0x00007f70e7881000)
	libPocoNetSSL.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoNetSSL.so.91 (0x00007f70e7834000)
	libPocoCrypto.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoCrypto.so.91 (0x00007f70e77e8000)
	libPocoRedis.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoRedis.so.91 (0x00007f70e77c0000)
	libPocoNet.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoNet.so.91 (0x00007f70e7666000)
	libPocoZip.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoZip.so.91 (0x00007f70e7622000)
	libPocoUtil.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoUtil.so.91 (0x00007f70e75a7000)
	libPocoJSON.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoJSON.so.91 (0x00007f70e753b000)
	libPocoXML.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoXML.so.91 (0x00007f70e74b8000)
	libPocoActiveRecord.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoActiveRecord.so.91 (0x00007f70e74ae000)
	libPocoData.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoData.so.91 (0x00007f70e7233000)
	libPocoFoundation.so.91 => /home/conan/.conan/data/poco/1.12.1/_/_/package/235590a09001f940efcdfddac7c4ba9ec3188883/lib/libPocoFoundation.so.91 (0x00007f70e704e000)
	libpcre2-posix.so.3 => /home/conan/.conan/data/pcre2/10.40/_/_/package/1d840f86edb049e4a49f0c00c2a2ca6e12c424f0/lib/libpcre2-posix.so.3 (0x00007f70e7918000)
	libpcre2-8.so.0 => /home/conan/.conan/data/pcre2/10.40/_/_/package/1d840f86edb049e4a49f0c00c2a2ca6e12c424f0/lib/libpcre2-8.so.0 (0x00007f70e6fe9000)
	libpcre2-16.so.0 => /home/conan/.conan/data/pcre2/10.40/_/_/package/1d840f86edb049e4a49f0c00c2a2ca6e12c424f0/lib/libpcre2-16.so.0 (0x00007f70e6f8f000)
	libpcre2-32.so.0 => /home/conan/.conan/data/pcre2/10.40/_/_/package/1d840f86edb049e4a49f0c00c2a2ca6e12c424f0/lib/libpcre2-32.so.0 (0x00007f70e6f39000)
	libexpat.so.1 => /home/conan/.conan/data/expat/2.4.8/_/_/package/941269f2bd298e56b0c2e3cd5d2647e3ff4fbd8a/lib/libexpat.so.1 (0x00007f70e6f08000)
	libsqlite3.so => /home/conan/.conan/data/sqlite3/3.38.5/_/_/package/3a131cb554f5d402417d952898a918d2ca261a79/lib/libsqlite3.so (0x00007f70e6dcc000)
	libpq.so.5 => /home/conan/.conan/data/libpq/14.2/_/_/package/a94498c1f63a7731916053a03adfbea7ef7657ad/lib/libpq.so.5 (0x00007f70e6d7c000)
	libmysqlclient.so.21 => /home/conan/.conan/data/libmysqlclient/8.0.29/_/_/package/ff3aea2a270668db914841937ccc9e1ebeb67343/lib/libmysqlclient.so.21 (0x00007f70e66ed000)
	libz.so.1 => /home/conan/.conan/data/zlib/1.2.12/_/_/package/a94498c1f63a7731916053a03adfbea7ef7657ad/lib/libz.so.1 (0x00007f70e66d1000)
	libbz2.so.1 => /home/conan/.conan/data/bzip2/1.0.8/_/_/package/e042af0ef4d34ae269eef1703cf65e36adf5a374/lib/libbz2.so.1 (0x00007f70e66b9000)
	libssl.so.1.1 => /home/conan/.conan/data/openssl/1.1.1o/_/_/package/a94498c1f63a7731916053a03adfbea7ef7657ad/lib/libssl.so.1.1 (0x00007f70e6625000)
	libcrypto.so.1.1 => /home/conan/.conan/data/openssl/1.1.1o/_/_/package/a94498c1f63a7731916053a03adfbea7ef7657ad/lib/libcrypto.so.1.1 (0x00007f70e6358000)
	libzstd.so.1 => /home/conan/.conan/data/zstd/1.5.2/_/_/package/db7f4a35f544af289ac2cf9a62a0e78b4739d23c/lib/libzstd.so.1 (0x00007f70e6284000)
	liblz4.so.1 => /home/conan/.conan/data/lz4/1.9.3/_/_/package/a94498c1f63a7731916053a03adfbea7ef7657ad/lib/liblz4.so.1 (0x00007f70e6252000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f70e5f40000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f70e5d25000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f70e5b21000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f70e5918000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f70e56fb000)
	libc++.so.1 => /usr/local/lib/libc++.so.1 (0x00007f70e55f4000)
	libgcc_s.so.1 => /usr/local/lib64/libgcc_s.so.1 (0x00007f70e53dc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f70e5012000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f70e78f1000)
	libatomic.so.1 => /usr/local/lib64/libatomic.so.1 (0x00007f70e4e09000)
```

**Comment by uilianries** [comment]
@jcar87 @jgsogo I just updated some tests, which validate the case that we no longer need `libunwind` for clang, when built with `libc++`.

After new PRs, new package versions, etc, we will replace them on Conan Center. The current Docker image is compatible as it still installs `libunwind` and those generated packages are compatible with `libgcc_s`.

Ready for a final review.

**Comment by jgsogo** [comment]
From the changeset I would say this is not breaking anything... but I really don't know the implications or internals (neither the actual issue) behind these changes.

---

> Doing more tests, now with Poco, build with Clang 13, but current one in Conan Center.
> 
> Poco requires `libllvm-unwind`, which is expected. So, any next library or example which requires it, will need `libllvm-unwind`. This new patch will enforce `libgcc_s` with clang and will keep `libllvm-unwind` installed for the legacy. So it passed with Poco.
> 
> With a new `clang13-ubuntu16.04:1.50.0` image, using `libgcc_s`, consuming Poco and building all dependencies from source, I have:
> 

The check that should worry us more is about **reusing existing binaries**... if building (and running) Poco with requirements downloaded from ConanCenter (built using _previous_ docker image) work inside this image.

**Comment by uilianries** [comment]
> The check that should worry us more is about reusing existing binaries... if building (and running) Poco with requirements downloaded from ConanCenter (built using previous docker image) work inside this image.

Yes, this is the most sensible case. Poco was only validation, but the first case came from Protobuf, where an user complained about "missing libllvm-unwind". I also tested with Protobuf, using this new image and worked. So far, they look very compatible.

**Comment by uilianries** [comment]
During the last build some error occurred to build Clang:

- The Clang build image install cmake and ninja from pip
- Both pip packages now require Python 3.6
- Ubuntu 16.04 (Xenial) only supports Python 3.5 officially
- Whitesnake, a non-official PPA, but very popular, no longer support Python 3.6 for Ubuntu Xenial
- There are other PPAs, but still, not official
- New approach: Install both CMake and Ninja from official repositories
- CMake and Ninja versions don't matter, they are only required to build Clang from source.

**Comment by jgsogo** [comment]
If we are starting to have compatibility issues with 16.04, maybe it is time to start thinking about the next LTS version, wdyt? In any case, not something for this PR.

**Review by jgsogo — APPROVED** [review]
LGTM

**Comment by uilianries** [comment]
> If we are starting to have compatibility issues with 16.04, maybe it is time to start thinking about the next LTS version, wdyt? In any case, not something for this PR.

Yes. We could start to think about Ubuntu 18.04 or even some minimal approach with Alpine, like it was commented in the past.

**Pull request merged**
