### PR TITLE
Bump version to 1.29.1

### PR DESCRIPTION
**Pull request by ericLemanissier**
Changelog: Feature: Bump Conan version to 1.29.1

this will unblock at least the following:
- https://github.com/conan-io/conan-center-index/pull/2741
- https://github.com/conan-io/conan-center-index/pull/2303
- https://github.com/conan-io/conan-center-index/pull/2301

### CODE REVIEW

**Comment by ericLemanissier** [comment]
1 job errored with `ERROR: Error 500 downloading file https://github.com/google/googletest/archive/release-1.8.1.tar.gz`
Probably you can use "Rerun failed jobs" button ?

**Comment by uilianries** [comment]
Finally they added re-run failed jobs!

@ericLemanissier thanks for your PR. We have to wait more 1 or 2 weeks before merging it. As CCI consumes the latest Docker image available, it will create a problem if merged now. In the future it should be fixed for CCI.

**Comment by Croydon** [comment]
> As CCI consumes the latest Docker image available, it will create a problem if merged now.

What problem would this cause?

**Comment by uilianries** [comment]
We can't different versions at same time. Windows and OSX builders are machines, so we need to update them all same time. Imagine a recipe which requires Conan 1.29 failing on Windows because Conan is outdated, but it pass on Linux.

**Review by uilianries — APPROVED** [review]

**Pull request merged**
