### PR TITLE
Fix Clang 7 testing

### PR DESCRIPTION
**Pull request by Croydon**

### CODE REVIEW

**Comment by Croydon** [comment]
Okay, this uncovers the next problem:

> E: Version '1:7-2' for 'clang-7' was not found

https://packages.ubuntu.com/cosmic/clang-7

The version exists, why can't it be found?

and unrelated but still important: GCC 8 fails with package conflicts
> The following packages have unmet dependencies:
 dh-autoreconf : Depends: debhelper but it is not going to be installed
                 Depends: libtool (>= 2.4.2) but it is not going to be installed
 g++-8-multilib : Depends: g++-8 (= 8-20180414-1ubuntu2) but it is not going to be installed
                  Depends: gcc-8-multilib (= 8-20180414-1ubuntu2) but it is not going to be installed
                  Depends: lib32stdc++-8-dev (= 8-20180414-1ubuntu2) but it is not going to be installed
                  Depends: libx32stdc++-8-dev (= 8-20180414-1ubuntu2) but it is not going to be installed

**Comment by lasote** [comment]
Related with: https://github.com/conan-io/conan/pull/3643
I would like first to clarify the whole situation/solution.

**Comment by Croydon** [comment]
Thanks for the reference.

> The version exists, why can't it be found?

Seems like the web UI is lagging behind the actually package versions. Fixed.

**Comment by Croydon** [comment]
Closing due to https://github.com/conan-io/conan-docker-tools/commit/2bf548562114b2c62707e354071ab10f7662457c and #61

**Pull request closed without merging**
