### PR TITLE
upload clang70:latest too

### LINKED ISSUE #156: missing tag conanio/clang70:latest
as mentionned https://github.com/conan-io/conan-docker-tools/pull/147#issuecomment-545426585:
I'm not a docker expert, but it looks like this PR does not properly create the latest tag for conanio/clang70 image: https://dev.azure.com/bincrafters/packages/_build/results?buildId=612
there is no latest tag here https://hub.docker.com/r/conanio/clang70/tags?page=1 contrary to https://hub.docker.com/r/conanio/clang7/tags?page=1
https://github.com/conan-io/conan-docker-tools/pull/155 does seem to create the tag, but it is not uploaded.

### PR DESCRIPTION
**Pull request by ericLemanissier**
fixes #156

Changelog: (Feature | Fix | Bugfix): Describe here your pull request

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan-docker-tools/blob/master/.github/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008) style guides for Python code.
- [x] I've followed the [Best Practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) guides for Dockerfile.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
@uilianries this is a blind guess. What do you think ?

**Comment by uilianries** [comment]
oh boy, I forgot it! I updated the job to generate the image, and the docker compose script, which I thought was enough to upload it. But indeed the upload process is part of this script. I check now the Docker hub repo and clang70:latest is not there.

**Comment by uilianries** [comment]
@ericLemanissier Go ahead! You PR looks good

**Comment by ericLemanissier** [comment]
@uilianries @lasote what do you think ?

**Pull request merged**
