### PR TITLE
Refactoring Docker images

### PR DESCRIPTION
**Pull request by uilianries**
Hi!

I just started to refactoring the images, but I'll keep this PR as [work-in-progress] in order to receive  comments during this task. As we have many images, the final state before to merge can be huge and tedious to review.

For now, I reduced about 100MB from conangcc63

Regards.

### CODE REVIEW

**Comment by lasote** [comment]
Nice, keep working, it looks all ok!

**Comment by uilianries** [comment]
@lasote What do you think about add Docker Compose support?

We won't remove build.py, but the build/run stages could be done by docker-compose.

**Comment by uilianries** [comment]
@lasote It's done. Please, review the changes.

**Comment by uilianries** [comment]
Up!

**Comment by lasote** [comment]
All looks nice, about the Docker compose, I don't know much about it. 
Will try to fix the CI and merge this.
Thanks!

**Pull request merged**
